site_name: fiware-android
site_url: https://github.com/atooma/fiware-android-wiki
site_description: DOC for private fiware-android repo
site_author: Federico Di Pierro

repo_url: https://github.com/atooma/fiware-android-wiki

pages:
- Home: README.md
- Getting started: Getting-started-with-fiware-android.md
- Fiware: Fiware:-an-open-and-simple-help-for-developers.md
- Prject: Project-info.md
- GAE-fiware: GAE-fiware-server.md
- Development: Devel.md
